# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    paths:
      - 'Projects/P4/**'
  pull_request:
    paths:
      - 'Projects/P4/**'
  workflow_dispatch:
    paths:
      - 'Projects/P4/**'

defaults:
  run:
    working-directory: Projects/P4/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile src files
        run: |
          javac -cp "junit-4.10.jar:." *.java


  TestGhostInRange:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          javac -cp "junit-4.10.jar:." *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestGhostInRange


  TestPacmanInRange:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          javac -cp "junit-4.10.jar:." *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestPacmanInRange


  TestMapAttack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          javac -cp "junit-4.10.jar:." *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestMapAttack

    