# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    paths:
      - 'Projects/P4/**'
  pull_request:
    paths:
      - 'Projects/P4/**'
  workflow_dispatch:
    paths:
      - 'Projects/P4/**'

defaults:
  run:
    working-directory: Projects/P4/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile src files
        run: |
          javac -cp "src/" src/*.java

  # Job to test PacMan.get_valid_moves()
  pacmangetvalidmoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile and run PacMan's get_valid_moves() test, testPacManValidMoves
        run: |
	  javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
	  java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves

  # Job to test Ghost.get_valid_moves()
  ghostgetvalidmoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile and run Ghost's get_valid_moves() test, testGhostValidMoves
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves

  # Job to test PacMan.get_valid_moves()
  mapmove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile and run Map's move() test, testMapMove
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove
